on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, ready_for_review, reopened]
name: automerge
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@ef030fabb510b9a5a3bc2e3a0123638e11e72541"
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
