on: push
name: Main
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - run: npm ci
    - name: TypeScript
      run: ./node_modules/.bin/tsc
    - name: Rollup
      run: ./node_modules/.bin/rollup -c
